function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 30-Apr-2026 10:45:22


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Ax_mean', 'Ax_var', 'Ax_rms', 'Ax_range', 'Ax_peakFreq', 'Ax_meanPower', 'Ax_peakPower', 'Ax_specEnt', 'Ay_mean', 'Ay_var', 'Ay_rms', 'Ay_range', 'Ay_peakFreq', 'Ay_meanPower', 'Ay_peakPower', 'Ay_specEnt', 'Az_mean', 'Az_var', 'Az_rms', 'Az_range', 'Az_peakFreq', 'Az_meanPower', 'Az_peakPower', 'Az_specEnt', 'SMV_Acc_mean', 'SMV_Acc_var', 'SMV_Acc_rms', 'SMV_Acc_range', 'SMV_Acc_peakFreq', 'SMV_Acc_meanPower', 'SMV_Acc_peakPower', 'SMV_Acc_specEnt', 'Gx_mean', 'Gx_var', 'Gx_rms', 'Gx_range', 'Gx_peakFreq', 'Gx_meanPower', 'Gx_peakPower', 'Gx_specEnt', 'Gy_mean', 'Gy_var', 'Gy_rms', 'Gy_range', 'Gy_peakFreq', 'Gy_meanPower', 'Gy_peakPower', 'Gy_specEnt', 'Gz_mean', 'Gz_var', 'Gz_rms', 'Gz_range', 'Gz_peakFreq', 'Gz_meanPower', 'Gz_peakPower', 'Gz_specEnt', 'SMV_Gyr_mean', 'SMV_Gyr_var', 'SMV_Gyr_rms', 'SMV_Gyr_range', 'SMV_Gyr_peakFreq', 'SMV_Gyr_meanPower', 'SMV_Gyr_peakPower', 'SMV_Gyr_specEnt'};
predictors = inputTable(:, predictorNames);
response = inputTable.Material;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'120 Grit'; '40 Grit'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationNeuralNetwork = fitcnet(...
    predictors, ...
    response, ...
    'LayerSizes', 25, ...
    'Activations', 'relu', ...
    'Lambda', 0, ...
    'IterationLimit', 1000, ...
    'Standardize', true, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
neuralNetworkPredictFcn = @(x) predict(classificationNeuralNetwork, x);
trainedClassifier.predictFcn = @(x) neuralNetworkPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'Ax_mean', 'Ax_var', 'Ax_rms', 'Ax_range', 'Ax_peakFreq', 'Ax_meanPower', 'Ax_peakPower', 'Ax_specEnt', 'Ay_mean', 'Ay_var', 'Ay_rms', 'Ay_range', 'Ay_peakFreq', 'Ay_meanPower', 'Ay_peakPower', 'Ay_specEnt', 'Az_mean', 'Az_var', 'Az_rms', 'Az_range', 'Az_peakFreq', 'Az_meanPower', 'Az_peakPower', 'Az_specEnt', 'SMV_Acc_mean', 'SMV_Acc_var', 'SMV_Acc_rms', 'SMV_Acc_range', 'SMV_Acc_peakFreq', 'SMV_Acc_meanPower', 'SMV_Acc_peakPower', 'SMV_Acc_specEnt', 'Gx_mean', 'Gx_var', 'Gx_rms', 'Gx_range', 'Gx_peakFreq', 'Gx_meanPower', 'Gx_peakPower', 'Gx_specEnt', 'Gy_mean', 'Gy_var', 'Gy_rms', 'Gy_range', 'Gy_peakFreq', 'Gy_meanPower', 'Gy_peakPower', 'Gy_specEnt', 'Gz_mean', 'Gz_var', 'Gz_rms', 'Gz_range', 'Gz_peakFreq', 'Gz_meanPower', 'Gz_peakPower', 'Gz_specEnt', 'SMV_Gyr_mean', 'SMV_Gyr_var', 'SMV_Gyr_rms', 'SMV_Gyr_range', 'SMV_Gyr_peakFreq', 'SMV_Gyr_meanPower', 'SMV_Gyr_peakPower', 'SMV_Gyr_specEnt'};
trainedClassifier.ClassificationNeuralNetwork = classificationNeuralNetwork;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2025b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Ax_mean', 'Ax_var', 'Ax_rms', 'Ax_range', 'Ax_peakFreq', 'Ax_meanPower', 'Ax_peakPower', 'Ax_specEnt', 'Ay_mean', 'Ay_var', 'Ay_rms', 'Ay_range', 'Ay_peakFreq', 'Ay_meanPower', 'Ay_peakPower', 'Ay_specEnt', 'Az_mean', 'Az_var', 'Az_rms', 'Az_range', 'Az_peakFreq', 'Az_meanPower', 'Az_peakPower', 'Az_specEnt', 'SMV_Acc_mean', 'SMV_Acc_var', 'SMV_Acc_rms', 'SMV_Acc_range', 'SMV_Acc_peakFreq', 'SMV_Acc_meanPower', 'SMV_Acc_peakPower', 'SMV_Acc_specEnt', 'Gx_mean', 'Gx_var', 'Gx_rms', 'Gx_range', 'Gx_peakFreq', 'Gx_meanPower', 'Gx_peakPower', 'Gx_specEnt', 'Gy_mean', 'Gy_var', 'Gy_rms', 'Gy_range', 'Gy_peakFreq', 'Gy_meanPower', 'Gy_peakPower', 'Gy_specEnt', 'Gz_mean', 'Gz_var', 'Gz_rms', 'Gz_range', 'Gz_peakFreq', 'Gz_meanPower', 'Gz_peakPower', 'Gz_specEnt', 'SMV_Gyr_mean', 'SMV_Gyr_var', 'SMV_Gyr_rms', 'SMV_Gyr_range', 'SMV_Gyr_peakFreq', 'SMV_Gyr_meanPower', 'SMV_Gyr_peakPower', 'SMV_Gyr_specEnt'};
predictors = inputTable(:, predictorNames);
response = inputTable.Material;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'120 Grit'; '40 Grit'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationNeuralNetwork, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
